[package]
name = "forktest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "forktest"
path = "src/main.rs"

[dependencies]
libkenix = { path = "../libkenix" }

[profile.release]
opt-level = "z"      # Optimize for size
lto = true
codegen-units = 1
panic = "abort"