[workspace]
resolver = "2"
members = [
    "libkenix",
    "console",
    "init",
    "vfs",
    "hello",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"      # Optimize for size
lto = true
